const express = require('express');
const cors = require('cors');
const cookieParser = require('cookie-parser');
const axios = require('axios');

const app = express();
const PORT = process.env.PORT || 3001;

// --- CONFIGURATION ---
const FRONTEND_URL = process.env.FRONTEND_URL;
const LEARNWORLDS_SCHOOL_URL = process.env.LEARNWORLDS_SCHOOL_URL;

if (!FRONTEND_URL || !LEARNWORLDS_SCHOOL_URL) {
    console.error("Critical environment variables are missing!");
    process.exit(1);
}

// --- MIDDLEWARE ---
// Trust the first proxy. Important for Heroku.
app.set('trust proxy', 1);

// CORS configuration to allow requests ONLY from your Vercel frontend
app.use(cors({
    origin: FRONTEND_URL,
    credentials: true // This is crucial for cookies to be sent and received
}));
app.use(cookieParser());


// --- DATABASE OF QUESTIONS ---
const allQuestions = [
    // --- Processo Civil ---
    {
        id: 1,
        discipline: "Processo Civil",
        code: "Código de Processo Civil",
        articleNumber: "Artigo 186.º",
        articleTitle: "Ineptidão da petição inicial",
        articleText: "1 - É nulo todo o processo quando for inepta a petição inicial.\n2 - Diz-se inepta a petição:\na) Quando falte ou seja ininteligível a indicação do pedido ou da causa de pedir;\nb) Quando o pedido esteja em contradição com a causa de pedir;\nc) Quando se cumulem causas de pedir ou pedidos substancialmente incompatíveis.",
        question: "Quando é que a petição inicial é considerada inepta?",
        options: [
            "Apenas quando falta a indicação do pedido.",
            "Quando falta ou é ininteligível o pedido ou a causa de pedir, há contradição entre eles, ou cumulação de pedidos/causas de pedir incompatíveis.",
            "Sempre que o valor da causa não é indicado corretamente.",
            "Quando não são juntas todas as provas documentais."
        ],
        correctAnswerIndex: 1,
        explanation: "O Art. 186.º, n.º 2, elenca as três situações que levam à ineptidão da petição inicial, todas relacionadas com a clareza e coerência do pedido e da causa de pedir, que são elementos essenciais da petição."
    },
    {
        id: 2,
        discipline: "Processo Civil",
        code: "Código de Processo Civil",
        articleNumber: "Artigo 574.º",
        articleTitle: "Ónus de impugnação",
        articleText: "1 - Ao contestar, deve o réu tomar posição definida perante os factos que constituem a causa de pedir invocada pelo autor.\n2 - Consideram-se admitidos por acordo os factos que não forem impugnados, salvo se estiverem em oposição com a defesa considerada no seu conjunto, se não for admissível confissão sobre eles ou se só puderem ser provados por documento escrito; a admissão de factos instrumentais pode ser afastada por prova posterior.",
        question: "Qual é a consequência regra da não impugnação de um facto alegado pelo autor na petição inicial?",
        options: [
            "O juiz deve investigar oficiosamente se o facto é verdadeiro.",
            "O facto considera-se admitido por acordo.",
            "O processo é imediatamente anulado.",
            "O autor tem de provar o facto através de testemunhas."
        ],
        correctAnswerIndex: 1,
        explanation: "O Art. 574.º, n.º 2, consagra o princípio do ónus de impugnação especificada. A inércia do réu em contestar um facto leva a que o mesmo seja considerado como aceite, dispensando a sua prova pelo autor, salvo as exceções previstas na lei."
    },
    {
        id: 3,
        discipline: "Processo Civil",
        code: "Código de Processo Civil",
        articleNumber: "Artigo 266.º",
        articleTitle: "Admissibilidade da reconvenção",
        articleText: "1 - O réu pode, em reconvenção, deduzir pedidos contra o autor.\n2 - A reconvenção é admissível nos seguintes casos:\na) Quando o pedido do réu emerja do facto jurídico que serve de fundamento à ação ou à defesa;\nb) Quando o réu se propõe obter a compensação ou tornar efetivo o direito a benfeitorias ou despesas relativas à coisa cuja entrega lhe é pedida;\nc) Quando o pedido do réu tende a conseguir, em seu benefício, o mesmo efeito jurídico que o autor se propõe obter.",
        question: "Em que situação NÃO é admissível a reconvenção?",
        options: [
            "Quando o réu pretende obter a compensação de um crédito.",
            "Quando o pedido do réu emerge do mesmo facto jurídico da ação.",
            "Quando o réu deduz um pedido completamente novo e sem qualquer conexão com a ação ou a defesa.",
            "Quando o réu quer obter para si o mesmo efeito jurídico que o autor."
        ],
        correctAnswerIndex: 2,
        explanation: "A reconvenção não é um meio para o réu iniciar uma ação qualquer contra o autor. O Art. 266.º, n.º 2, exige uma conexão entre o pedido reconvencional e a ação principal, seja através do facto jurídico, da compensação/benfeitorias, ou da identidade do efeito jurídico pretendido."
    },
    {
        id: 4,
        discipline: "Processo Civil",
        code: "Código de Processo Civil",
        articleNumber: "Artigo 591.º",
        articleTitle: "Finalidades da audiência prévia",
        articleText: "1 - A audiência prévia destina-se a:\na) Realizar tentativa de conciliação, nos termos do artigo 594.º;\nb) Facultar às partes a discussão de facto e de direito, nos casos em que ao juiz cumpra apreciar exceções dilatórias ou quando tencione conhecer imediatamente, no todo ou em parte, do mérito da causa;\nc) Discutir as posições das partes, com vista à delimitação dos litígios;\nd) Proferir despacho saneador, nos termos do n.º 1 do artigo 595.º;\ne) Determinar, após debate, a adequação formal, a simplificação ou a agilização do processado;\nf) Proferir, após debate, o despacho previsto no n.º 1 do artigo 596.º e decidir as reclamações deduzidas pelas partes;\ng) Programar, após debate, os atos a realizar na audiência final, o número de sessões e a sua provável duração.",
        question: "Qual das seguintes NÃO é uma finalidade da audiência prévia?",
        options: [
            "Realizar a produção de prova testemunhal.",
            "Tentar a conciliação entre as partes.",
            "Proferir o despacho saneador.",
            "Delimitar os temas da prova."
        ],
        correctAnswerIndex: 0,
        explanation: "A produção de prova testemunhal é o ato central da audiência final, não da audiência prévia. A audiência prévia, conforme o Art. 591.º, tem como finalidades a gestão processual, a tentativa de conciliação e a preparação da fase de julgamento."
    },
    {
        id: 5,
        discipline: "Processo Civil",
        code: "Código de Processo Civil",
        articleNumber: "Artigo 604.º",
        articleTitle: "Discussão e julgamento da causa",
        articleText: "1 - Finda a produção da prova, pode cada um dos advogados fazer uma alegação oral, para resumir as conclusões, de facto e de direito, que extrai da prova produzida.\n2 - Nas suas alegações, os advogados não podem, sob pena de multa, invocar factos que não tenham sido alegados nos articulados ou factos notórios de que o tribunal não se tenha servido nos termos do artigo 412.º; o tribunal não toma em conta, na decisão, os factos invocados em contravenção do disposto neste número.\n3 - A discussão oral é dirigida pelo juiz, que pode, a todo o tempo, a limitar, nos termos do artigo 522.º, ou retirar a palavra ao advogado que se afaste do devido respeito pelo tribunal, pelas instituições ou pelo advogado da parte contrária, sem prejuízo do procedimento criminal ou disciplinar que ao caso couber.\n4 - O juiz pode, a todo o tempo, durante a discussão oral, pedir às partes os esclarecimentos que entender necessários.\n5 - Encerrada a discussão, o juiz profere logo a sentença, que é ditada para a ata, podendo, porém, o julgamento ser adiado por um período não superior a 10 dias, se as questões de facto ou de direito a resolver se revelarem de especial complexidade.\n6 - O juiz que não proferir a sentença no prazo previsto no número anterior é sancionado nos termos do artigo 152.º.",
        question: "Após a produção de prova em audiência final, qual é, por regra, o passo seguinte?",
        options: [
            "A interposição de recurso.",
            "As alegações orais dos advogados.",
            "A apresentação de novos articulados.",
            "A realização de uma nova audiência prévia."
        ],
        correctAnswerIndex: 1,
        explanation: "Conforme o Art. 604.º, n.º 1, uma vez terminada a produção de prova (depoimentos, perícias, etc.), a fase seguinte é a das alegações orais, onde os advogados expõem as suas conclusões de facto e de direito. Só depois das alegações é que o juiz profere a sentença."
    },
    {
        id: 6,
        discipline: "Processo Civil",
        code: "Código de Processo Civil",
        articleNumber: "Artigo 615.º",
        articleTitle: "Causas de nulidade da sentença",
        articleText: "1 - É nula a sentença quando:\na) Não contenha a assinatura do juiz;\nb) Não especifique os fundamentos de facto e de direito que justificam a decisão;\nc) Os fundamentos estejam em oposição com a decisão ou ocorra alguma ambiguidade ou obscuridade que torne a decisão ininteligível;\nd) O juiz deixe de pronunciar-se sobre questões que devesse apreciar ou conheça de questões de que não podia tomar conhecimento;\ne) O juiz condene em quantidade superior ou em objeto diverso do pedido.",
        question: "O juiz condena o réu a pagar 15.000€, quando o autor tinha pedido apenas 10.000€. De que vício padece a sentença?",
        options: [
            "É um erro de julgamento, passível de recurso.",
            "É uma nulidade, por condenação em quantidade superior ao pedido (excesso de pronúncia).",
            "A sentença é perfeitamente válida.",
            "É uma omissão de pronúncia."
        ],
        correctAnswerIndex: 1,
        explanation: "O Art. 615.º, n.º 1, alínea e), sanciona com a nulidade as sentenças que condenem 'em quantidade superior ou em objeto diverso do pedido'. Esta é uma violação do princípio do dispositivo, que limita a decisão do juiz ao que foi pedido pelas partes."
    },
    { id: 7, discipline: "Processo Civil", code: "Código de Processo Civil", articleNumber: "Artigo 588.º", articleTitle: "Termos em que são admitidos", articleText: "1 - Os factos constitutivos, modificativos ou extintivos do direito que forem supervenientes podem ser deduzidos em articulado posterior ou em novo articulado, pela parte a quem aproveitem, até ao encerramento da discussão.\n2 - Dizem-se supervenientes tanto os factos ocorridos posteriormente ao termo dos prazos marcados nos artigos precedentes como os factos anteriores de que a parte só tenha conhecimento depois de findarem esses prazos, devendo neste caso produzir-se prova da superveniência.", question: "Uma parte tem conhecimento de um facto relevante para a causa após a audiência prévia. Em que momento deve apresentar o articulado superveniente?", options: ["A qualquer momento, até ao trânsito em julgado.", "Na própria audiência final.", "Nos 10 dias posteriores à notificação da data designada para a audiência final.", "Apenas se a parte contrária concordar."], correctAnswerIndex: 2, explanation: "De acordo com a alínea b) do n.º 3 do Artigo 588.º, se não houver audiência prévia ou os factos forem conhecidos após esta, o articulado superveniente deve ser oferecido nos 10 dias posteriores à notificação da data da audiência final." },
    { id: 8, discipline: "Processo Civil", code: "Código de Processo Civil", articleNumber: "Artigo 590.º", articleTitle: "Gestão inicial do processo", articleText: "4 - Incumbe ainda ao juiz convidar as partes ao suprimento das insuficiências ou imprecisões na exposição ou concretização da matéria de facto alegada, fixando prazo para a apresentação de articulado em que se complete ou corrija o inicialmente produzido.", question: "Após a fase dos articulados, o juiz verifica que a exposição da matéria de facto pelo autor é imprecisa. O que deve fazer?", options: ["Indeferir liminarmente a petição.", "Convidar o autor a aperfeiçoar o articulado, fixando um prazo para o efeito.", "Absolver o réu da instância por ineptidão da petição.", "Marcar imediatamente a audiência final."], correctAnswerIndex: 1, explanation: "O Art. 590.º, n.º 4, consagra o dever de gestão processual, impondo ao juiz que convide as partes a suprir insuficiências ou imprecisões na exposição da matéria de facto." },
    { id: 9, discipline: "Processo Civil", code: "Código de Processo Civil", articleNumber: "Artigo 245.º", articleTitle: "Dilação", articleText: "1 - Ao prazo de defesa do citando acresce uma dilação de cinco dias quando:\na) A citação tenha sido realizada em pessoa diversa do réu...\n2 - Quando o réu haja sido citado para a causa no território das Regiões Autónomas, correndo a ação no continente ou em outra ilha, ou vice-versa, a dilação é de 15 dias.\n5 - A dilação resultante do disposto na alínea a) do n.º 1 acresce à que eventualmente resulte do estabelecido na alínea b) e nos n.os 2 e 3.", question: "Numa ação que corre em Lisboa, o réu é citado na Madeira, na pessoa da sua mãe. Qual a dilação total aplicável?", options: ["15 dias.", "5 dias.", "20 dias.", "Não há dilação."], correctAnswerIndex: 2, explanation: "A citação nas Regiões Autónomas confere 15 dias de dilação (n.º 2) e a citação em pessoa diversa do réu acrescenta 5 dias (n.º 1, al. a)). As dilações são cumuláveis (n.º 5), totalizando 20 dias." },
    { id: 10, discipline: "Processo Civil", code: "Código de Processo Civil", articleNumber: "Artigo 366.º", articleTitle: "Contraditório do requerido", articleText: "3 - A dilação, quando a ela haja lugar nos termos do artigo 245.º, nunca pode exceder a duração de 10 dias.", question: "No âmbito de um procedimento cautelar, um requerido foi citado numa ilha das Regiões Autónomas, sendo a ação intentada em Lisboa. Qual é o prazo de dilação aplicável?", options: ["30 dias.", "15 dias.", "10 dias.", "Não há lugar a dilação."], correctAnswerIndex: 2, explanation: "Apesar de a regra geral do Art. 245.º prever uma dilação de 15 dias, o Art. 366.º, n.º 3, estabelece uma regra especial para os procedimentos cautelares, limitando qualquer dilação a um máximo de 10 dias devido à urgência do processo." },
    { id: 11, discipline: "Processo Civil", code: "Código de Processo Civil", articleNumber: "Artigo 149.º", articleTitle: "Regra geral sobre o prazo", articleText: "1 - Na falta de disposição especial, é de 10 dias o prazo para as partes requererem qualquer ato ou diligência... e também é de 10 dias o prazo para a parte responder ao que for deduzido pela parte contrária.", question: "A lei não prevê um prazo específico para uma parte responder a um requerimento da parte contrária. Qual é o prazo aplicável?", options: ["5 dias.", "30 dias.", "10 dias.", "O juiz fixa o prazo."], correctAnswerIndex: 2, explanation: "O Art. 149.º, n.º 1, estabelece o prazo supletivo geral de 10 dias para a prática de atos processuais para os quais a lei não preveja um prazo específico." },
    { id: 12, discipline: "Processo Civil", code: "Código de Processo Civil", articleNumber: "Artigo 33.º", articleTitle: "Litisconsórcio necessário", articleText: "1 - Se, porém, a lei ou o negócio exigir a intervenção dos vários interessados na relação controvertida, a falta de qualquer deles é motivo de ilegitimidade.", question: "Numa ação de preferência, o autor propõe a ação apenas contra o vendedor, omitindo o comprador. Qual a consequência processual?", options: ["O processo prossegue normalmente.", "O juiz deve suprir a falta.", "Verifica-se uma exceção dilatória de ilegitimidade.", "A ação é imediatamente julgada improcedente."], correctAnswerIndex: 2, explanation: "A ação de preferência exige a intervenção do vendedor e do comprador. A falta de um deles constitui preterição de litisconsórcio necessário (Art. 33.º, n.º 1), o que resulta na exceção dilatória de ilegitimidade (Art. 577.º, al. e))." },
    { id: 13, discipline: "Processo Civil", code: "Código de Processo Civil", articleNumber: "Artigo 37.º", articleTitle: "Obstáculos à coligação", articleText: "1 - A coligação não é admissível quando aos pedidos correspondam formas de processo diferentes ou a cumulação possa ofender regras de competência internacional ou em razão da matéria ou da hierarquia.", question: "Qual das seguintes situações constitui um obstáculo legal à coligação de réus numa ação?", options: ["Causas de pedir diferentes.", "Ofensa às regras de competência em razão da matéria.", "Domicílio em comarcas diferentes.", "Valor superior à alçada da Relação."], correctAnswerIndex: 1, explanation: "O Art. 37.º, n.º 1, estabelece que a ofensa às regras de competência em razão da matéria é um obstáculo direto à admissibilidade da coligação." },
    { id: 14, discipline: "Processo Civil", code: "Código de Processo Civil", articleNumber: "Artigo 40.º", articleTitle: "Constituição obrigatória de advogado", articleText: "1 - É obrigatória a constituição de advogado:\na) Nas causas de competência de tribunais com alçada, em que seja admissível recurso ordinário...", question: "Em que situação é obrigatória a constituição de advogado?", options: ["Em todas as ações cíveis.", "Apenas em ações de valor superior a 30.000 €.", "Nas causas de valor superior a 5.000 €.", "Apenas nos recursos para o Supremo Tribunal."], correctAnswerIndex: 2, explanation: "A constituição de advogado é obrigatória nas causas de valor superior à alçada do tribunal de 1.ª instância (5.000 €), pois são essas as causas em que é admissível recurso ordinário." },
    { id: 15, discipline: "Processo Civil", code: "Código de Processo Civil", articleNumber: "Artigo 41.º", articleTitle: "Falta de constituição de advogado", articleText: "Se a parte não constituir advogado, sendo obrigatória a constituição, o juiz... determina a sua notificação para o constituir dentro de prazo certo, sob pena de... ficar sem efeito a defesa.", question: "Numa ação em que é obrigatória a constituição de advogado, o réu apresenta contestação sem estar representado. Qual o procedimento correto?", options: ["Rejeitar liminarmente a contestação.", "Considerar o réu em revelia.", "Notificar o réu para constituir advogado em prazo certo.", "Absolver imediatamente o réu da instância."], correctAnswerIndex: 2, explanation: "O Art. 41.º estabelece o procedimento de sanação. O juiz deve notificar a parte para suprir a falta, e só se tal não for feito no prazo é que a cominação (defesa sem efeito) se aplica." },
    { id: 16, discipline: "Processo Civil", code: "Código de Processo Civil", articleNumber: "Artigo 96.º", articleTitle: "Casos de incompetência absoluta", articleText: "Determinam a incompetência absoluta do tribunal:\na) A infração das regras de competência em razão da matéria e da hierarquia...", question: "Uma ação sobre matéria da competência dos tribunais administrativos é proposta num tribunal judicial. De que vício padece o processo?", options: ["Incompetência relativa.", "Nulidade processual sanável.", "Incompetência absoluta.", "Erro na forma do processo."], correctAnswerIndex: 2, explanation: "A infração das regras de competência em razão da matéria determina a incompetência absoluta do tribunal (Art. 96.º, al. a)), que é uma exceção dilatória de conhecimento oficioso." },
    { id: 17, discipline: "Processo Civil", code: "Código de Processo Civil", articleNumber: "Artigo 102.º", articleTitle: "Em que casos se verifica", articleText: "A infração das regras de competência fundadas... na divisão judicial do território... determina a incompetência relativa do tribunal.", question: "Um autor propõe uma ação no tribunal do seu domicílio, quando a regra geral determinava a competência do tribunal do domicílio do réu. Qual a consequência?", options: ["Incompetência absoluta.", "Incompetência relativa, a ser arguida pelo réu.", "Nulidade da ação.", "O processo prossegue normalmente."], correctAnswerIndex: 1, explanation: "A violação das regras de competência territorial constitui, em regra, uma incompetência relativa (Art. 102.º), que deve ser arguida pelo réu na contestação (Art. 103.º)." },
    { id: 18, discipline: "Processo Civil", code: "Código de Processo Civil", articleNumber: "Artigo 281.º", articleTitle: "Deserção da instância e dos recursos", articleText: "1 - ...considera-se deserta a instância quando, por negligência das partes, o processo se encontre a aguardar impulso processual há mais de seis meses.", question: "Um processo declarativo está parado há sete meses por negligência do autor. O que acontece à instância?", options: ["A instância suspende-se.", "O réu é absolvido do pedido.", "A instância extingue-se por deserção, declarada por despacho.", "O juiz notifica novamente o autor."], correctAnswerIndex: 2, explanation: "O Art. 281.º, n.º 1, estabelece que a instância se considera deserta quando o processo fica parado por mais de seis meses por negligência das partes, devendo a deserção ser julgada por despacho." },
    { id: 19, discipline: "Processo Civil", code: "Código de Processo Civil", articleNumber: "Artigo 373.º", articleTitle: "Caducidade da providência", articleText: "1 - ...a providência caduca:\na) Se o requerente não propuser a ação da qual a providência depende dentro de 30 dias contados da data em que lhe tiver sido notificado o trânsito em julgado da decisão que a haja ordenado...", question: "Foi decretada uma providência cautelar. O requerente não propôs a ação principal no prazo legal. Qual a consequência?", options: ["A providência mantém-se.", "O requerido tem de pedir a revogação.", "A providência caduca por não proposição da ação principal em 30 dias.", "O requerente é condenado numa multa."], correctAnswerIndex: 2, explanation: "O Art. 373.º, n.º 1, al. a), determina a caducidade da providência se a ação principal não for instaurada no prazo de 30 dias, pois a providência é instrumental e dependente dessa ação." },
    { id: 20, discipline: "Processo Civil", code: "Código de Processo Civil", articleNumber: "Artigo 369.º", articleTitle: "Inversão do contencioso", articleText: "1 - ...o juiz, na decisão que decrete a providência, pode dispensar o requerente do ónus de propositura da ação principal se a matéria adquirida no procedimento lhe permitir formar convicção segura acerca da existência do direito acautelado...", question: "Para que o juiz possa decretar a inversão do contencioso, que requisito deve estar preenchido?", options: ["O valor da causa ser superior à alçada.", "O requerido concordar.", "A prova produzida permitir ao juiz formar uma convicção segura sobre o direito.", "A providência ter sido requerida como incidente."], correctAnswerIndex: 2, explanation: "O Art. 369.º, n.º 1, estabelece como requisito fundamental que a prova no procedimento cautelar seja tão robusta que permita ao juiz formar uma 'convicção segura' sobre o direito, tornando a ação principal desnecessária." },
    { id: 21, discipline: "Processo Civil", code: "Código de Processo Civil", articleNumber: "Artigo 423.º", articleTitle: "Momento da apresentação", articleText: "2 - Se não forem juntos com o articulado respetivo, os documentos podem ser apresentados até 20 dias antes da data em que se realize a audiência final, mas a parte é condenada em multa...", question: "Uma parte não juntou um documento com a sua petição inicial. Qual o prazo limite para o fazer, ainda que sujeito a multa?", options: ["Até ao encerramento da audiência final.", "10 dias após a petição.", "Até 20 dias antes da data da audiência final.", "Apenas na audiência prévia."], correctAnswerIndex: 2, explanation: "O Art. 423.º, n.º 2, estabelece um prazo limite de 20 dias antes da audiência final para a apresentação tardia de documentos, mediante o pagamento de multa." },
    { id: 22, discipline: "Processo Civil", code: "Código de Processo Civil", articleNumber: "Artigo 452.º", articleTitle: "Depoimento de parte", articleText: "1 - O juiz pode, em qualquer estado do processo, determinar a comparência pessoal das partes para a prestação de depoimento... sobre factos que interessem à decisão da causa.\n2 - Quando o depoimento seja requerido por alguma das partes, devem indicar-se logo, de forma discriminada, os factos sobre que há de recair.", question: "O principal objetivo do depoimento de parte requerido pela parte contrária é:", options: ["Substituir a prova testemunhal.", "Provocar a confissão da parte depoente.", "Permitir que a parte apresente a sua versão.", "Aclarar a matéria de direito."], correctAnswerIndex: 1, explanation: "O depoimento de parte, quando requerido pela parte contrária, destina-se a obter a confissão judicial sobre factos desfavoráveis ao depoente e favoráveis ao requerente." },
    { id: 23, discipline: "Processo Civil", code: "Código de Processo Civil", articleNumber: "Artigo 466.º", articleTitle: "Declarações de parte", articleText: "1 - As partes podem requerer... a prestação de declarações sobre factos em que tenham intervindo pessoalmente ou de que tenham conhecimento direto.", question: "Qual a principal diferença entre o depoimento de parte e as declarações de parte?", options: ["As declarações de parte não são gravadas.", "O depoimento só pode ser requerido pelo juiz.", "A iniciativa das declarações é da própria parte, enquanto o depoimento é da parte contrária ou do juiz.", "Nas declarações não se pode confessar."], correctAnswerIndex: 2, explanation: "A distinção fundamental reside na iniciativa: as declarações de parte são um meio de prova em que a própria parte se oferece para depor (Art. 466.º), enquanto o depoimento de parte é requerido pela parte contrária ou pelo juiz para obter a confissão (Art. 452.º)." },
    { id: 24, discipline: "Processo Civil", code: "Código de Processo Civil", articleNumber: "Artigo 598.º", articleTitle: "Apresentação do rol de testemunhas", articleText: "2 - O rol de testemunhas pode ser alterado ou aditado até 20 dias antes da data em que se realize a audiência final...", question: "Uma parte indicou o seu rol de testemunhas com a contestação. Pode alterá-lo posteriormente?", options: ["Não, o rol é imutável.", "Sim, livremente na audiência prévia.", "Sim, mas apenas até 20 dias antes da data da audiência final.", "Apenas com o consentimento da parte contrária."], correctAnswerIndex: 2, explanation: "O Art. 598.º, n.º 2, permite que o rol de testemunhas seja aditado ou alterado até 20 dias antes da data em que se realize a audiência final." },
    { id: 25, discipline: "Processo Civil", code: "Código de Processo Civil", articleNumber: "Artigo 629.º", articleTitle: "Decisões que admitem recurso", articleText: "1 - O recurso ordinário só é admissível quando a causa tenha valor superior à alçada do tribunal de que se recorre e a decisão impugnada seja desfavorável ao recorrente em valor superior a metade da alçada desse tribunal...", question: "Numa ação com o valor de 4.000 €, o réu foi condenado a pagar 3.000 €. Pode recorrer da decisão?", options: ["Sim, porque a sucumbência é superior a metade da alçada.", "Não, porque o valor da causa é inferior à alçada do tribunal.", "Sim, todas as sentenças são recorríveis.", "Não, porque a sucumbência é inferior à alçada."], correctAnswerIndex: 1, explanation: "O Art. 629.º, n.º 1, estabelece uma dupla condição para a recorribilidade. Neste caso, o valor da causa (4.000 €) é inferior à alçada da 1.ª instância (5.000 €), pelo que o recurso não é admissível." },
    { id: 26, discipline: "Processo Civil", code: "Código de Processo Civil", articleNumber: "Artigo 638.º", articleTitle: "Prazos", articleText: "1 - O prazo para a interposição do recurso é de 30 dias e conta-se a partir da notificação da decisão...", question: "Qual o prazo geral para a interposição de um recurso de apelação num processo comum?", options: ["15 dias.", "30 dias.", "10 dias.", "20 dias."], correctAnswerIndex: 1, explanation: "Conforme o Art. 638.º, n.º 1, o prazo geral para interposição de recurso é de 30 dias. O prazo de 15 dias é aplicável a processos urgentes e outras situações especificadas." },
    { id: 27, discipline: "Processo Civil", code: "Código de Processo Civil", articleNumber: "Artigo 671.º", articleTitle: "Decisões que comportam revista", articleText: "3 - ...não é admitida revista do acórdão da Relação que confirme, sem voto de vencido e sem fundamentação essencialmente diferente, a decisão proferida na 1.ª instância...", question: "O Tribunal da Relação confirma, sem voto de vencido e com fundamentação idêntica, uma decisão da 1.ª instância. É admissível recurso de revista?", options: ["Sim, se o valor da causa for superior a 30.000 €.", "Não, por regra, devido à 'dupla conforme'.", "Sim, sempre.", "Apenas se o recurso de apelação teve efeito suspensivo."], correctAnswerIndex: 1, explanation: "O Art. 671.º, n.º 3, consagra a regra da 'dupla conforme', que, por regra, impede o recurso de revista quando a Relação confirma a decisão da 1ª instância sem voto de vencido e com fundamentação semelhante." },
    { id: 28, discipline: "Processo Civil", code: "Código de Processo Civil", articleNumber: "Artigo 696.º", articleTitle: "Fundamentos do recurso", articleText: "A decisão transitada em julgado só pode ser objeto de revisão quando:\nc) Se apresente documento de que a parte não tivesse conhecimento... e que, por si só, seja suficiente para modificar a decisão...", question: "Qual das seguintes situações constitui fundamento para um recurso extraordinário de revisão?", options: ["A errada interpretação de uma norma.", "A descoberta de um novo acórdão em sentido contrário.", "A apresentação de um documento decisivo de que a parte não pôde fazer uso.", "A discordância com a apreciação da prova."], correctAnswerIndex: 2, explanation: "O Art. 696.º, al. c), prevê expressamente como fundamento de revisão a apresentação de um documento superveniente que seja, por si só, suficiente para modificar a decisão. Os outros são fundamentos de recurso ordinário." },
    { id: 29, discipline: "Processo Civil", code: "Código de Processo Civil", articleNumber: "Artigo 265.º", articleTitle: "Alteração do pedido e da causa de pedir na falta de acordo", articleText: "2 - O autor pode... ampliar o pedido até ao encerramento da discussão em 1.ª instância se a ampliação for o desenvolvimento ou a consequência do pedido primitivo.", question: "Na falta de acordo com o réu, em que circunstância pode o autor ampliar o pedido?", options: ["A qualquer momento e sem limite.", "Apenas na petição inicial.", "Até ao encerramento da discussão em 1ª instância, se for um desenvolvimento do pedido inicial.", "Nunca."], correctAnswerIndex: 2, explanation: "O Artigo 265.º, n.º 2, permite a ampliação do pedido sem acordo se ocorrer até ao encerramento da discussão em 1ª instância e for uma consequência lógica do pedido primitivo." },
    { id: 30, discipline: "Processo Civil", code: "Código de Processo Civil", articleNumber: "Artigo 139.º", articleTitle: "Modalidades do prazo", articleText: "5 - Independentemente de justo impedimento, pode o ato ser praticado dentro dos três primeiros dias úteis subsequentes ao termo do prazo, ficando a sua validade dependente do pagamento imediato de uma multa...", question: "O prazo para a prática de um ato judicial termina numa sexta-feira. Até quando pode a parte praticar o ato, pagando a respetiva multa?", options: ["Até à segunda-feira.", "Até à terça-feira.", "Até à quarta-feira.", "O prazo não pode ser ultrapassado."], correctAnswerIndex: 2, explanation: "O Artigo 139.º, n.º 5, permite a prática do ato nos três dias úteis subsequentes ao termo do prazo. Se o prazo terminou na sexta-feira, os três dias úteis seguintes são segunda-feira, terça-feira e quarta-feira." },
    { id: 31, discipline: "Processo Civil", code: "Código de Processo Civil", articleNumber: "Artigo 7.º", articleTitle: "Princípio da cooperação", articleText: "1 - Na condução e intervenção no processo, devem os magistrados, os mandatários judiciais e as próprias partes cooperar entre si...", question: "O princípio da cooperação, previsto no Artigo 7.º, impõe deveres a quem?", options: ["Apenas ao juiz.", "Apenas às partes e seus mandatários.", "Aos magistrados, aos mandatários judiciais e às próprias partes.", "Apenas às testemunhas e peritos."], correctAnswerIndex: 2, explanation: "O Artigo 7.º, n.º 1, é claro ao estabelecer que o dever de cooperação é recíproco e abrange todos os intervenientes processuais: magistrados, mandatários e as próprias partes." },

    // --- Processo Penal ---
    { id: 32, discipline: "Processo Penal", code: "Código de Processo Penal", articleNumber: "Artigo 50.º", articleTitle: "Legitimidade", articleText: "1 - O Ministério Público tem legitimidade para promover o processo penal, com as restrições constantes dos artigos 49.º a 52.º.", question: "Quem tem, por regra, a legitimidade para promover o processo penal em Portugal?", options: ["O ofendido.", "O juiz de instrução.", "O Ministério Público.", "O órgão de polícia criminal."], correctAnswerIndex: 2, explanation: "Conforme o Art. 50.º do CPP, o Ministério Público é o titular da ação penal, tendo legitimidade para a promover, salvo as exceções relativas a crimes semipúblicos e particulares." },
    { id: 33, discipline: "Processo Penal", code: "Código de Processo Penal", articleNumber: "Artigo 68.º", articleTitle: "Legitimidade e oportunidade da constituição de assistente", articleText: "1 - Podem constituir-se assistentes no processo penal, além das pessoas e entidades a quem leis especiais conferirem esse direito:\na) Os ofendidos, considerando-se como tais os titulares dos interesses que a lei especialmente quis proteger com a incriminação, desde que maiores de 16 anos;", question: "Quem pode, regra geral, constituir-se assistente num processo penal?", options: ["Qualquer cidadão.", "Apenas o Ministério Público.", "Os ofendidos, titulares dos interesses protegidos pela norma incriminadora.", "Apenas testemunhas do crime."], correctAnswerIndex: 2, explanation: "O Art. 68.º, n.º 1, al. a), estabelece que os ofendidos, definidos como os titulares dos interesses que a lei visa proteger, têm legitimidade para se constituírem assistentes." },
    { id: 34, discipline: "Processo Penal", code: "Código de Processo Penal", articleNumber: "Artigo 283.º", articleTitle: "Acusação pelo Ministério Público", articleText: "1 - Se durante o inquérito tiverem sido recolhidos indícios suficientes de se ter verificado crime e de quem foi o seu agente, o Ministério Público deduz acusação contra aquele.", question: "Em que circunstâncias o Ministério Público deduz acusação no final do inquérito?", options: ["Sempre que houver uma denúncia.", "Quando tiver a certeza absoluta da culpa do arguido.", "Quando tiverem sido recolhidos indícios suficientes da verificação do crime e de quem foi o seu agente.", "Apenas se o assistente o requerer."], correctAnswerIndex: 2, explanation: "O critério para a dedução da acusação, conforme o Art. 283.º, n.º 1, não é a certeza, mas a existência de 'indícios suficientes', ou seja, uma probabilidade razoável de condenação em julgamento." },
    { id: 35, discipline: "Processo Penal", code: "Código de Processo Penal", articleNumber: "Artigo 286.º", articleTitle: "Abertura da instrução", articleText: "1 - A instrução visa a comprovação judicial da decisão de deduzir acusação ou de arquivar o inquérito em ordem a submeter ou não a causa a julgamento.", question: "Qual é a finalidade principal da fase de instrução?", options: ["Repetir o julgamento.", "Permitir ao arguido apresentar novas provas não consideradas no inquérito.", "A comprovação judicial da decisão de acusar ou de arquivar o inquérito.", "Aplicar imediatamente uma pena ao arguido."], correctAnswerIndex: 2, explanation: "A instrução, como define o Art. 286.º, n.º 1, é uma fase facultativa que serve de controlo jurisdicional (por um juiz) da decisão do Ministério Público no final do inquérito." },
    { id: 36, discipline: "Processo Penal", code: "Código de Processo Penal", articleNumber: "Artigo 311.º", articleTitle: "Saneamento do processo", articleText: "1 - Recebidos os autos no tribunal de julgamento, o presidente despacha no sentido de sanear o processo, conhecendo das nulidades e de outras questões prévias ou incidentais que obstem à apreciação do mérito da causa...", question: "Qual é o objetivo do despacho de saneamento do processo antes do julgamento?", options: ["Decidir imediatamente a culpa do arguido.", "Conhecer de nulidades e outras questões prévias que possam impedir a apreciação do mérito.", "Marcar a data da audiência.", "Ouvir as testemunhas pela primeira vez."], correctAnswerIndex: 1, explanation: "O Art. 311.º estabelece que a primeira função do juiz de julgamento é 'sanear' o processo, ou seja, verificar se existem vícios processuais (nulidades, exceções) que devam ser resolvidos antes de se passar à fase de audiência." },
    { id: 37, discipline: "Processo Penal", code: "Código de Processo Penal", articleNumber: "Artigo 196.º", articleTitle: "Termo de identidade e residência", articleText: "1 - A autoridade judiciária ou o órgão de polícia criminal sujeitam a termo de identidade e residência todo aquele que for constituído arguido.", question: "Qual é a medida de coação que, por regra, é aplicada a toda a pessoa constituída arguida?", options: ["Prisão preventiva.", "Caução.", "Obrigação de permanência na habitação.", "Termo de identidade e residência (TIR)."], correctAnswerIndex: 3, explanation: "O Art. 196.º, n.º 1, estabelece que o Termo de Identidade e Residência (TIR) é a medida de coação base, aplicada a qualquer pessoa constituída arguida, implicando deveres como o de não mudar de residência sem comunicar." },
    { id: 38, discipline: "Processo Penal", code: "Código de Processo Penal", articleNumber: "Artigo 202.º", articleTitle: "Requisitos gerais de aplicação das medidas de coação", articleText: "1 - Nenhuma medida de coação, à exceção do termo de identidade e residência, pode ser aplicada se em concreto se não verificarem:\na) Fuga ou perigo de fuga;\nb) Perigo de perturbação do decurso do inquérito ou da instrução do processo e, nomeadamente, perigo para a aquisição, conservação ou veracidade da prova; ou\nc) Perigo, em razão da natureza e das circunstâncias do crime ou da personalidade do arguido, de que este continue a atividade criminosa ou perturbe gravemente a ordem e a tranquilidade públicas.", question: "Qual dos seguintes é um requisito geral para a aplicação de uma medida de coação (exceto o TIR)?", options: ["A confissão do arguido.", "O valor do dano ser superior a 5.000€.", "A existência de perigo de fuga, perturbação do processo ou continuação da atividade criminosa.", "A concordância do defensor."], correctAnswerIndex: 2, explanation: "O Art. 202.º, n.º 1, elenca os 'pericula' (perigos) que devem ser demonstrados para que qualquer medida de coação mais gravosa que o TIR possa ser aplicada, como o perigo de fuga." },
    { id: 39, discipline: "Processo Penal", code: "Código de Processo Penal", articleNumber: "Artigo 227.º", articleTitle: "Caução económica", articleText: "1 - Se houver fundado receio de que faltem ou diminuam substancialmente as garantias do pagamento da pena pecuniária, das custas do processo ou de qualquer outra dívida para com o Estado relacionada com o crime, pode ser exigida ao arguido a prestação de uma caução económica.", question: "Qual é a finalidade da medida de garantia patrimonial de caução económica?", options: ["Garantir a presença do arguido em tribunal.", "Assegurar o pagamento de multas, custas ou outras dívidas ao Estado relacionadas com o crime.", "Impedir que o arguido contacte as testemunhas.", "Compensar imediatamente a vítima."], correctAnswerIndex: 1, explanation: "Ao contrário das medidas de coação, que visam fins processuais, as medidas de garantia patrimonial, como a caução económica prevista no Art. 227.º, destinam-se a garantir as consequências patrimoniais do crime." },
    { id: 40, discipline: "Processo Penal", code: "Código de Processo Penal", articleNumber: "Artigo 125.º", articleTitle: "Legalidade da prova", articleText: "São admissíveis as provas que não forem proibidas por lei.", question: "Qual o princípio basilar relativo à admissibilidade da prova em processo penal?", options: ["Princípio da livre convicção do juiz.", "Princípio da legalidade, segundo o qual só são admissíveis provas não proibidas por lei.", "Princípio do inquisitório.", "Princípio da prova mais favorável ao arguido."], correctAnswerIndex: 1, explanation: "O Art. 125.º consagra o princípio da legalidade da prova (ou da tipicidade), que estabelece que a regra é a da admissibilidade, sendo a inadmissibilidade a exceção, que tem de estar prevista na lei." },
    { id: 41, discipline: "Processo Penal", code: "Código de Processo Penal", articleNumber: "Artigo 126.º", articleTitle: "Métodos proibidos de prova", articleText: "1 - São nulas, não podendo ser utilizadas, as provas obtidas mediante tortura, coação ou, em geral, ofensa da integridade física ou moral das pessoas.", question: "Uma confissão obtida através de ameaças a um familiar do arguido é uma prova válida?", options: ["Sim, se a confissão for confirmada por outras provas.", "Não, é uma prova nula e não pode ser utilizada.", "Depende da gravidade do crime.", "Sim, porque a ameaça não foi dirigida diretamente ao arguido."], correctAnswerIndex: 1, explanation: "O Art. 126.º estabelece uma proibição absoluta de prova. Qualquer prova obtida através de ofensa à integridade física ou moral, como a coação por ameaça, é nula e não pode ser valorada no processo." },
    { id: 42, discipline: "Processo Penal", code: "Código de Processo Penal", articleNumber: "Artigo 174.º", articleTitle: "Pressupostos", articleText: "1 - A revista de pessoas e a busca de lugares ou recintos que não constituam domicílio só podem ser ordenadas ou autorizadas por despacho da autoridade judiciária competente, quando houver fundados indícios de que alguém oculta na sua pessoa ou num desses lugares quaisquer animais, coisas ou objetos relacionados com um crime...", question: "Qual é o pressuposto para a realização de uma busca a um veículo?", options: ["A mera suspeita de um crime.", "A autorização do proprietário do veículo.", "Fundados indícios de que no veículo se ocultam objetos relacionados com um crime.", "A existência de uma queixa formal."], correctAnswerIndex: 2, explanation: "O Art. 174.º, n.º 1, exige um grau qualificado de suspeita ('fundados indícios') para que se possa comprimir o direito à reserva da vida privada através de uma busca a um local que, como um veículo, não constitui domicílio." },
    { id: 43, discipline: "Processo Penal", code: "Código de Processo Penal", articleNumber: "Artigo 177.º", articleTitle: "Busca domiciliária", articleText: "1 - A busca em casa habitada ou numa sua dependência fechada só pode ser ordenada ou autorizada pelo juiz e efetuada entre as 7 e as 21 horas, sob pena de nulidade.", question: "Uma busca a uma residência é realizada às 22 horas, sem o consentimento do morador. Qual a consequência?", options: ["É uma mera irregularidade.", "A prova encontrada é válida se for relevante.", "O ato é nulo.", "O ato é válido se for autorizado pelo Ministério Público."], correctAnswerIndex: 2, explanation: "O Art. 177.º, n.º 1, estabelece regras estritas para a busca domiciliária, incluindo a sua realização durante o dia (7h-21h). A realização da busca fora deste horário, sem consentimento, constitui uma nulidade expressamente cominada na lei." },
    { id: 44, discipline: "Processo Penal", code: "Código de Processo Penal", articleNumber: "Artigo 399.º", articleTitle: "Recorribilidade", articleText: "É permitido recorrer:\na) De acórdãos, sentenças e despachos cuja irrecorribilidade não estiver prevista na lei;\nb) De despachos que ponham termo ao processo;\nc) De despachos que, após o encerramento do inquérito ou da instrução, não admitam a constituição de assistente ou de parte civil ou os considerem partes ilegítimas.", question: "Qual é a regra geral em matéria de recorribilidade de decisões em processo penal?", options: ["Apenas as sentenças finais são recorríveis.", "Nenhuma decisão interlocutória é recorrível.", "A regra é a da recorribilidade, salvo nos casos em que a lei preveja a irrecorribilidade.", "Apenas as decisões do juiz de instrução são recorríveis."], correctAnswerIndex: 2, explanation: "O Art. 399.º, al. a), estabelece o princípio geral da recorribilidade. Ao contrário do processo civil, onde a regra é a da irrecorribilidade em separado das decisões interlocutórias, no processo penal a regra é a de que as decisões são recorríveis, a menos que a lei diga o contrário." },
    { id: 45, discipline: "Processo Penal", code: "Código de Processo Penal", articleNumber: "Artigo 400.º", articleTitle: "Decisões que não admitem recurso", articleText: "1 - Não é admissível recurso:\n a) Dos despachos de mero expediente;\n b) Dos acórdãos proferidos, em recurso, pelas relações, que não ponham termo à causa;\n c) De acórdãos absolutórios proferidos, em recurso, pelas relações, exceto no caso de condenação em 1.ª instância em pena de prisão superior a 5 anos...", question: "Um tribunal da Relação, em recurso, revoga uma condenação de 1 ano de prisão e absolve o arguido. O assistente pode recorrer desta decisão para o Supremo Tribunal de Justiça?", options: ["Sim, sempre.", "Não, por regra, os acórdãos absolutórios da Relação não admitem recurso.", "Sim, se o Ministério Público também recorrer.", "Apenas se a pena aplicada em 1ª instância fosse superior a 8 anos."], correctAnswerIndex: 1, explanation: "O Art. 400.º, n.º 1, al. c), consagra a regra da irrecorribilidade dos acórdãos absolutórios da Relação. A exceção (condenação em 1ª instância a pena superior a 5 anos) não se aplica neste caso, pelo que a decisão se torna definitiva." },
    { id: 46, discipline: "Processo Penal", code: "Código de Processo Penal", articleNumber: "Artigo 411.º", articleTitle: "Prazo de interposição", articleText: "1 - O prazo para interposição de recurso é de 30 dias e conta-se:\na) Da notificação da decisão;\nb) Tratando-se de decisão oral reproduzida em ata, do dia em que foi proferida, se o arguido estiver ou dever considerar-se presente...", question: "Qual é o prazo geral para a interposição de recurso de uma sentença penal?", options: ["15 dias.", "20 dias.", "30 dias.", "10 dias."], correctAnswerIndex: 2, explanation: "De forma semelhante ao processo civil, o Art. 411.º, n.º 1, estabelece que o prazo regra para interposição de recurso em processo penal é de 30 dias." },
    { id: 47, discipline: "Processo Penal", code: "Código de Processo Penal", articleNumber: "Artigo 432.º", articleTitle: "Decisões de que se pode recorrer para o Supremo Tribunal de Justiça", articleText: "1 - Recorre-se para o Supremo Tribunal de Justiça:\na) De decisões das relações proferidas em 1.ª instância;\nb) De decisões que ponham termo à causa proferidas pelos tribunais de júri ou pelo tribunal coletivo que apliquem pena de prisão superior a 5 anos...", question: "Um tribunal coletivo condena um arguido a uma pena de 4 anos de prisão. Para que tribunal deve ser interposto o recurso?", options: ["Para o Tribunal da Relação.", "Diretamente para o Supremo Tribunal de Justiça.", "Para o Tribunal Constitucional.", "A decisão é irrecorrível."], correctAnswerIndex: 0, explanation: "O Art. 432.º, n.º 1, al. b), estabelece que o recurso 'per saltum' (direto) para o STJ só é possível para condenações superiores a 5 anos de prisão. Abaixo desse patamar, e nos termos do Art. 427.º, o recurso é interposto para o Tribunal da Relação." },
    { id: 48, discipline: "Processo Penal", code: "Código de Processo Penal", articleNumber: "Artigo 118.º", articleTitle: "Princípio da legalidade", articleText: "1 - A violação ou a inobservância das disposições da lei do processo penal só determina a nulidade do ato quando esta for expressamente cominada na lei.\n2 - Nos casos em que a lei não cominar a nulidade, o ato ilegal é irregular.", question: "A violação de uma norma processual penal, para a qual a lei não prevê expressamente a sanção da nulidade, constitui o quê?", options: ["Um ato nulo.", "Uma irregularidade.", "Um ato inexistente.", "Um ato anulável."], correctAnswerIndex: 1, explanation: "O Art. 118.º consagra o princípio da legalidade ou da tipicidade em matéria de invalidades processuais. Se a sanção não for a nulidade (expressamente prevista), o ato é considerado meramente irregular." },
    { id: 49, discipline: "Processo Penal", code: "Código de Processo Penal", articleNumber: "Artigo 119.º", articleTitle: "Nulidades insanáveis", articleText: "Constituem nulidades insanáveis, que devem ser oficiosamente declaradas em qualquer fase do procedimento, além das que como tal forem cominadas em outras disposições legais:\na) A falta do número de juízes ou de jurados que devam constituir o tribunal, bem como a falta de promoção do processo pelo Ministério Público e a sua ausência a atos em que deva estar presente...", question: "Qual das seguintes situações constitui uma nulidade insanável?", options: ["A falta de notificação de um despacho de mero expediente.", "A ausência do Ministério Público no debate instrutório.", "Um erro na contagem de um prazo processual.", "A falta de assinatura do defensor num requerimento simples."], correctAnswerIndex: 1, explanation: "O Art. 119.º, al. a), prevê expressamente como nulidade insanável, de conhecimento oficioso a todo o tempo, a ausência do Ministério Público a atos em que a sua presença é obrigatória, como o debate instrutório." },
    { id: 50, discipline: "Processo Penal", code: "Código de Processo Penal", articleNumber: "Artigo 120.º", articleTitle: "Nulidades dependentes de arguição", articleText: "2 - Constituem nulidades dependentes de arguição, além das que como tal forem cominadas em outras disposições legais:\na) O inquérito ou a instrução por entidade incompetente;\nb) A falta de nomeação de defensor ao arguido que o não tenha constituído...", question: "O arguido é interrogado no inquérito sem a presença de um defensor, apesar de a sua assistência ser legalmente obrigatória. De que vício padece o ato?", options: ["É uma nulidade insanável.", "É uma nulidade sanável (dependente de arguição).", "É uma mera irregularidade.", "O ato é perfeitamente válido."], correctAnswerIndex: 1, explanation: "A falta de assistência por defensor nos casos em que a lei a exige, como num interrogatório de arguido detido, constitui uma nulidade dependente de arguição, prevista no Art. 120.º, n.º 2, al. c) (não transcrita, mas relevante para a resposta)." },
    { id: 51, discipline: "Processo Penal", code: "Código de Processo Penal", articleNumber: "Artigo 122.º", articleTitle: "Declaração da nulidade", articleText: "1 - As nulidades insanáveis devem ser oficiosamente declaradas em qualquer fase do procedimento.\n2 - As nulidades dependentes de arguição devem ser arguidas:\na) Tratando-se de nulidade de ato a que o interessado assista, antes que o ato termine;\nb) Tratando-se da nulidade do inquérito ou da instrução, até ao encerramento do debate instrutório ou, não havendo instrução, até cinco dias após a notificação do despacho que tiver encerrado o inquérito...", question: "Qual o prazo regra para arguir uma nulidade sanável ocorrida durante o inquérito, não havendo instrução?", options: ["A qualquer momento.", "Até 5 dias após a notificação do despacho de encerramento do inquérito.", "Apenas na contestação.", "Até ao início da audiência de julgamento."], correctAnswerIndex: 1, explanation: "O Art. 122.º, n.º 2, al. b), estabelece um prazo preclusivo para a arguição de nulidades da fase de inquérito, que é de 5 dias após a notificação do despacho que lhe põe termo (acusação ou arquivamento)." },
    { id: 52, discipline: "Processo Penal", code: "Código de Processo Penal", articleNumber: "Artigo 123.º", articleTitle: "Irregularidades", articleText: "1 - Qualquer irregularidade do processo só determina a invalidade do ato a que se refere e dos termos subsequentes que possa afetar quando tiver sido arguida pelos interessados no próprio ato ou, se a este não tiverem assistido, nos três dias seguintes a contar daquele em que tiverem sido notificados para qualquer termo do processo ou intervindo em algum ato nele praticado.", question: "Qual o prazo para arguir uma irregularidade processual?", options: ["Apenas no recurso da decisão final.", "A qualquer momento, por ser de conhecimento oficioso.", "No prazo geral de 10 dias.", "No próprio ato ou nos 3 dias seguintes a contar da notificação para qualquer termo do processo."], correctAnswerIndex: 3, explanation: "O Art. 123.º, n.º 1, estabelece um prazo muito curto para a arguição de irregularidades, devendo ser feita de imediato (no próprio ato) ou, subsidiariamente, no prazo de 3 dias após a notificação para qualquer ato subsequente." },
    { id: 53, discipline: "Processo Penal", code: "Código de Processo Penal", articleNumber: "Artigo 104.º", articleTitle: "Princípios gerais", articleText: "1 - Os atos processuais praticam-se nos dias úteis, às horas de expediente dos serviços de justiça e fora do período de férias judiciais. \n2 - Excetuam-se do disposto no número anterior os atos processuais relativos a arguidos detidos ou presos, ou indispensáveis para garantir a liberdade das pessoas, e os atos de inquérito e de instrução que o interesse da investigação ou do ensino exigir que se pratiquem continuadamente ou com urgência.", question: "Um interrogatório judicial de um arguido detido pode ser realizado durante as férias judiciais?", options: ["Não, nenhum ato processual pode ser realizado em férias judiciais.", "Sim, porque se trata de um ato relativo a arguido detido e indispensável para garantir a sua liberdade.", "Apenas com o consentimento do arguido e do Ministério Público.", "Não, salvo se o crime for punível com pena superior a 8 anos de prisão."], correctAnswerIndex: 1, explanation: "O Art. 104.º, n.º 2, prevê uma exceção à regra da suspensão dos prazos em férias judiciais para os atos relativos a arguidos detidos ou presos, dada a urgência e a importância dos direitos fundamentais em causa." },
    { id: 54, discipline: "Processo Penal", code: "Código de Processo Penal", articleNumber: "Artigo 105.º", articleTitle: "Forma de contagem", articleText: "1 - A contagem dos prazos para a prática de atos processuais é feita nos termos do disposto no artigo 279.º do Código Civil.\n2 - Correm em férias judiciais os prazos relativos a processos nos quais devam praticar-se os atos referidos no n.º 2 do artigo anterior.", question: "A contagem do prazo para requerer a abertura de instrução num processo com arguido detido suspende-se durante as férias judiciais?", options: ["Sim, todos os prazos se suspendem em férias judiciais.", "Depende da decisão do juiz.", "Não, por ser um processo urgente com arguido detido, o prazo corre em férias judiciais.", "Apenas se o crime for público."], correctAnswerIndex: 2, explanation: "O Art. 105.º, n.º 2, em conjugação com o Art. 104.º, n.º 2, estabelece que nos processos com arguidos detidos ou presos (considerados urgentes), os prazos não se suspendem e correm continuamente, mesmo durante as férias judiciais." },
    { id: 55, discipline: "Processo Penal", code: "Código de Processo Penal", articleNumber: "Artigo 107.º", articleTitle: "Prazo e seu excesso", articleText: "2 - O excesso do prazo judicial por tempo não superior a três dias não implica a caducidade do direito de praticar o ato, se a parte provar que o excesso não lhe é imputável.", question: "Um advogado adoece subitamente no último dia do prazo para apresentar um recurso. O que pode fazer?", options: ["O prazo extingue-se e não pode fazer nada.", "Pode praticar o ato fora do prazo se provar o justo impedimento.", "Pode praticar o ato nos 3 dias seguintes, pagando uma multa.", "Tem de pedir autorização ao juiz para prolongar o prazo."], correctAnswerIndex: 1, explanation: "A situação descrita (doença súbita) enquadra-se no conceito de justo impedimento. O Art. 107.º, n.º 2 (remetendo para o CPC), permite a prática do ato fora do prazo, desde que a parte prove a ocorrência de um evento imprevisível e que a impediu de praticar o ato atempadamente." },
    { id: 56, discipline: "Processo Penal", code: "Código de Processo Penal", articleNumber: "Artigo 107.º-A", articleTitle: "Prática de ato processual fora do prazo", articleText: "1 - Sem prejuízo do disposto no n.º 2 do artigo anterior, o ato processual pode ser praticado fora do prazo, nos três dias úteis subsequentes, ficando a sua validade dependente do pagamento imediato de uma multa.", question: "O prazo para contestar termina numa segunda-feira. Até quando pode a parte, no máximo, apresentar a contestação, pagando a respetiva multa?", options: ["Até terça-feira.", "Até quarta-feira.", "Até quinta-feira.", "O prazo não pode ser ultrapassado."], correctAnswerIndex: 2, explanation: "O Art. 107.º-A permite a prática do ato nos três dias úteis subsequentes ao termo do prazo, mediante o pagamento de uma multa. Se o prazo terminou na segunda-feira, os três dias úteis seguintes são terça-feira, quarta-feira e quinta-feira." },
   
    // --- Deontologia ---
    { id: 57, discipline: "Deontologia", code: "Estatuto da Ordem dos Advogados", articleNumber: "Artigo 88.º", articleTitle: "Integridade", articleText: "1 - O advogado é indispensável à administração da justiça e, como tal, deve ter um comportamento público e profissional adequado à dignidade e à responsabilidade da função que exerce, cumprindo pontual e escrupulosamente os deveres consignados no presente Estatuto e todos aqueles que a lei, os usos, os costumes e as tradições profissionais lhe impõem.", question: "O princípio da integridade, previsto no Art. 88.º do EOA, exige do advogado um comportamento adequado apenas na sua vida profissional?", options: ["Sim, apenas nos atos praticados enquanto advogado.", "Não, exige um comportamento adequado tanto na vida pública como profissional.", "Apenas perante os tribunais.", "Apenas na relação com os clientes."], correctAnswerIndex: 1, explanation: "O Art. 88.º, n.º 1, é claro ao estipular que o advogado deve ter um 'comportamento público e profissional adequado', o que significa que os seus deveres de dignidade e responsabilidade se estendem para além da prática de atos meramente processuais." },
    { id: 58, discipline: "Deontologia", code: "Estatuto da Ordem dos Advogados", articleNumber: "Artigo 89.º", articleTitle: "Independência", articleText: "1 - O advogado, no exercício da profissão, deve manter sempre e em quaisquer circunstâncias a sua independência, devendo agir livre de qualquer pressão, especialmente a que resulte dos seus próprios interesses ou de influências exteriores, abstendo-se de negligenciar a deontologia profissional no intuito de agradar ao seu cliente, aos colegas, ao tribunal ou a terceiros.", question: "Um advogado aceita alterar uma peça processual contra as suas convicções jurídicas apenas para agradar a um cliente importante. Que princípio deontológico está a violar?", options: ["O dever de sigilo profissional.", "O princípio da independência.", "O dever de urbanidade.", "O dever de lealdade para com o cliente."], correctAnswerIndex: 1, explanation: "O Art. 89.º, n.º 1, estabelece que o advogado deve agir livre de qualquer pressão, incluindo a de 'agradar ao seu cliente'. A sua atuação deve pautar-se pela lei e pela deontologia, e não pela vontade do cliente quando esta colide com as suas convicções técnico-jurídicas." },
    { id: 59, discipline: "Deontologia", code: "Estatuto da Ordem dos Advogados", articleNumber: "Artigo 92.º", articleTitle: "Segredo profissional", articleText: "1 - O advogado é obrigado a guardar segredo profissional no que respeita a todos os factos cujo conhecimento lhe advenha do exercício das suas funções ou da prestação dos seus serviços...", question: "Um cidadão consulta um advogado sobre um problema, mas decide não lhe conferir mandato. O advogado fica, ainda assim, vinculado ao segredo profissional?", options: ["Não, porque não foi celebrado contrato de mandato.", "Apenas se o cliente tiver pago a consulta.", "Sim, o dever de segredo profissional abrange todos os factos de que o advogado toma conhecimento no exercício das suas funções, mesmo que não venha a ser contratado.", "Não, a menos que o cidadão o peça expressamente."], correctAnswerIndex: 2, explanation: "O dever de segredo profissional é uma obrigação fundamental e abrange todos os factos conhecidos 'do exercício das suas funções ou da prestação dos seus serviços', o que inclui uma consulta preliminar, independentemente da celebração de um contrato de mandato (Art. 92.º, n.º 1)." },
    { id: 60, discipline: "Deontologia", code: "Estatuto da Ordem dos Advogados", articleNumber: "Artigo 95.º", articleTitle: "Dever geral de urbanidade", articleText: "1 - No exercício da profissão, o advogado deve proceder com urbanidade, nomeadamente para com os colegas, os magistrados, os árbitros, os peritos, as testemunhas e demais intervenientes nos processos...", question: "O dever de urbanidade aplica-se a quem?", options: ["Apenas na relação com outros advogados.", "Apenas na relação com os juízes.", "A todos os intervenientes nos processos, incluindo colegas, magistrados, testemunhas, etc.", "Apenas aos clientes."], correctAnswerIndex: 2, explanation: "O Art. 95.º, n.º 1, impõe um dever geral de comportamento cortês e respeitoso para com todos os intervenientes processuais, sem exceção, como forma de garantir a dignidade da justiça e da profissão." },
    { id: 61, discipline: "Deontologia", code: "Estatuto da Ordem dos Advogados", articleNumber: "Artigo 99.º", articleTitle: "Conflito de interesses", articleText: "1 - O advogado deve recusar o patrocínio de uma questão em que já tenha intervindo em qualquer qualidade ou seja conexa com outra em que represente, ou tenha representado, a parte contrária.", question: "Um advogado representou o Autor numa ação de divórcio. Anos mais tarde, o Réu dessa mesma ação procura o mesmo advogado para o representar numa ação de regulação de responsabilidades parentais contra o Autor. Pode o advogado aceitar?", options: ["Sim, porque são processos diferentes.", "Apenas com autorização da Ordem dos Advogados.", "Não, porque a questão é conexa com outra em que representou a parte contrária, existindo um conflito de interesses.", "Sim, se o cliente pagar honorários mais elevados."], correctAnswerIndex: 2, explanation: "O Art. 99.º, n.º 1, proíbe o patrocínio em questões conexas com outras em que o advogado tenha representado a parte contrária. Sendo o divórcio e as responsabilidades parentais matérias conexas, o advogado está impedido de aceitar o mandato para evitar um conflito de interesses." },
    { id: 62, discipline: "Deontologia", code: "Estatuto da Ordem dos Advogados", articleNumber: "Artigo 67.º", articleTitle: "Atos da profissão", articleText: "1 - Sem prejuízo do disposto na Lei n.º 49/2004, de 24 de agosto, são atos próprios de advogado e de solicitador os que visem o exercício do mandato forense.", question: "Qual é considerado o ato por excelência próprio dos advogados?", options: ["A elaboração de contratos.", "A consulta jurídica.", "O exercício do mandato forense.", "A autenticação de documentos."], correctAnswerIndex: 2, explanation: "O Art. 67.º do EOA, em conjugação com a Lei dos Atos Próprios, define o mandato forense (a representação de uma parte em juízo) como o núcleo central dos atos próprios de advogado." },
    { id: 63, discipline: "Deontologia", code: "Estatuto da Ordem dos Advogados", articleNumber: "Artigo 81.º", articleTitle: "Incompatibilidades", articleText: "1 - O exercício da advocacia é incompatível com o exercício de qualquer outra função, profissão ou atividade que diminua a independência e a dignidade da profissão.", question: "Qual é o critério geral para determinar se uma atividade é incompatível com o exercício da advocacia?", options: ["Se a outra atividade é menos remunerada.", "Se a outra atividade exige mais de 20 horas semanais.", "Se a outra atividade diminui a independência e a dignidade da profissão de advogado.", "Se a outra atividade não está relacionada com o Direito."], correctAnswerIndex: 2, explanation: "O Art. 81.º, n.º 1, estabelece a cláusula geral: a incompatibilidade existe sempre que outra função ou atividade possa comprometer os pilares da advocacia, nomeadamente a independência e a dignidade." },
    { id: 64, discipline: "Deontologia", code: "Estatuto da Ordem dos Advogados", articleNumber: "Artigo 196.º", articleTitle: "Competência", articleText: "1 - Compete ao advogado estagiário, sob a direção e responsabilidade do patrono, praticar os seguintes atos:\na) Todos os atos da competência dos solicitadores;\nb) Exercer a consulta jurídica.", question: "Um advogado estagiário, sob a orientação do seu patrono, pode dar uma consulta jurídica a um cliente?", options: ["Não, a consulta jurídica é um ato exclusivo de advogados com inscrição definitiva.", "Apenas por escrito e com a assinatura conjunta do patrono.", "Sim, a consulta jurídica é um dos atos que o estagiário pode praticar sob a direção do patrono.", "Apenas em processos de valor inferior à alçada da Relação."], correctAnswerIndex: 2, explanation: "O Art. 196.º, n.º 1, alínea b), prevê expressamente que o advogado estagiário tem competência para exercer a consulta jurídica, desde que o faça sob a direção e responsabilidade do seu patrono." },
    { id: 65, discipline: "Deontologia", code: "Estatuto da Ordem dos Advogados", articleNumber: "Artigo 76.º", articleTitle: "Buscas, apreensões e diligências em escritório de advogado ou sociedade de advogados", articleText: "1 - A busca e a apreensão em escritório de advogado ou em sociedade de advogados... são, sob pena de nulidade, presididas pelo juiz de instrução.", question: "Uma busca realizada a um escritório de advogado, sem ser presidida por um juiz de instrução, é válida?", options: ["Sim, se for autorizada pelo Ministério Público.", "Sim, se o advogado der o seu consentimento.", "Não, a diligência é nula.", "Depende dos objetos a apreender."], correctAnswerIndex: 2, explanation: "O Art. 76.º, n.º 1, estabelece uma garantia fundamental para a proteção do segredo profissional e da independência da advocacia. A presença do juiz de instrução é um requisito de validade, cuja falta gera a nulidade do ato." },
    { id: 66, discipline: "Deontologia", code: "Estatuto da Ordem dos Advogados", articleNumber: "Artigo 77.º", articleTitle: "Reclamação", articleText: "1 - A violação das garantias previstas nos artigos 75.º e 76.º pode ser reclamada para o presidente do tribunal da Relação, com recurso para o pleno da secção criminal.", question: "Caso as regras de uma busca a um escritório de advogado sejam violadas, qual o mecanismo de reação imediato previsto no EOA?", options: ["Apresentar queixa-crime contra os agentes.", "Recorrer da decisão que autorizou a busca.", "Apresentar uma reclamação para o presidente do Tribunal da Relação.", "Participar disciplinarmente ao Conselho Superior da Magistratura."], correctAnswerIndex: 2, explanation: "O Art. 77.º prevê um mecanismo específico e célere de reação à violação das garantias em sede de buscas, que é a reclamação dirigida ao presidente do Tribunal da Relação competente." },
    { id: 67, discipline: "Deontologia", code: "Estatuto da Ordem dos Advogados", articleNumber: "Artigo 90.º", articleTitle: "Deveres para com a comunidade", articleText: "1 - O advogado está obrigado a defender os direitos, liberdades e garantias, a pugnar pela boa aplicação das leis, pela rápida administração da justiça e pelo aperfeiçoamento da cultura e instituições jurídicas.", question: "Qual dos seguintes é um dever do advogado para com a comunidade?", options: ["Garantir sempre a vitória do seu cliente.", "Pugnar pela rápida administração da justiça.", "Cobrar os honorários mais baixos possíveis.", "Aceitar todas as causas que lhe sejam propostas."], correctAnswerIndex: 1, explanation: "O Art. 90.º, n.º 1, consagra a função social do advogado, que transcende o mero interesse do seu cliente. Pugnar pela rápida e eficaz administração da justiça é um dever para com a comunidade em geral." },
    { id: 68, discipline: "Deontologia", code: "Estatuto da Ordem dos Advogados", articleNumber: "Artigo 91.º", articleTitle: "Deveres para com a Ordem dos Advogados", articleText: "1 - O advogado tem o dever de colaborar com a Ordem dos Advogados, de exercer os cargos para que tenha sido eleito ou nomeado e de desempenhar os mandatos que lhe forem confiados.", question: "Um advogado que é eleito para um cargo na Ordem dos Advogados pode recusar-se a exercê-lo sem justificação?", options: ["Sim, o exercício de cargos é voluntário.", "Não, o exercício de cargos para que foi eleito é um dever deontológico.", "Apenas pode recusar se não for remunerado.", "Sim, mas fica impedido de votar nas eleições seguintes."], correctAnswerIndex: 1, explanation: "O Art. 91.º, n.º 1, estabelece que o exercício de cargos para os quais um advogado foi eleito ou nomeado é um dever para com a Ordem, e não uma mera faculdade." },
    { id: 69, discipline: "Deontologia", code: "Estatuto da Ordem dos Advogados", articleNumber: "Artigo 100.º", articleTitle: "Deveres para com o cliente", articleText: "1 - Nas relações com o cliente, o advogado deve:\na) Dar a sua opinião conscienciosa sobre o merecimento do direito ou pretensão que o cliente invoca, assim como prestar, sempre que lhe for solicitado, informação sobre o andamento das questões que lhe forem confiadas...", question: "Um cliente pede ao seu advogado informações sobre o estado do seu processo. O advogado recusa-se a informar. Está a violar um dever?", options: ["Não, o advogado só tem de prestar contas no final do processo.", "Apenas se o cliente pagar um valor adicional por essa informação.", "Sim, está a violar o dever de informação sobre o andamento das questões.", "Não, porque a gestão do processo é da sua exclusiva competência."], correctAnswerIndex: 2, explanation: "O Art. 100.º, n.º 1, alínea a), impõe ao advogado um claro dever de manter o cliente informado sobre o andamento do processo, sempre que tal lhe seja solicitado." },
    { id: 70, discipline: "Deontologia", code: "Estatuto da Ordem dos Advogados", articleNumber: "Artigo 103.º", articleTitle: "Fixação e moderação dos honorários", articleText: "1 - Os honorários do advogado devem ser fixados em montante que represente uma compensação económica adequada pelos serviços efetivamente prestados, que deve ser moderada...", question: "Qual o critério principal para a fixação de honorários?", options: ["O valor da causa.", "O resultado obtido.", "Devem ser adequados aos serviços prestados e moderados.", "A tabela de honorários mínimos da Ordem dos Advogados."], correctAnswerIndex: 2, explanation: "O Art. 103.º, n.º 1, estabelece que os honorários devem ser uma compensação 'adequada' e 'moderada', devendo ser ponderados diversos fatores, como o tempo despendido, a complexidade do assunto, etc., conforme detalhado no n.º 3 do mesmo artigo." },
    { id: 71, discipline: "Deontologia", code: "Estatuto da Ordem dos Advogados", articleNumber: "Artigo 106.º", articleTitle: "Pactum de quota litis", articleText: "1 - É proibido ao advogado celebrar o pacto de «quota litis».\n2 - Diz-se «quota litis» o acordo celebrado entre o advogado e o seu cliente, antes da conclusão definitiva da questão em que este é parte, pelo qual o direito a honorários fique exclusivamente dependente do resultado obtido na questão...", question: "Um advogado acorda com um cliente que apenas receberá honorários se ganhar a causa, correspondendo a 30% do valor obtido. Este acordo é válido?", options: ["Sim, é uma forma de partilha de risco.", "Apenas se o valor não exceder 20% do resultado.", "Não, é um pacto de 'quota litis', proibido pelo EOA.", "Sim, se for reduzido a escrito."], correctAnswerIndex: 2, explanation: "O Art. 106.º proíbe expressamente o pacto de 'quota litis', que se caracteriza por fazer os honorários dependerem exclusivamente do resultado e consistirem numa parte do mesmo. O acordo descrito enquadra-se perfeitamente nesta proibição." },
    { id: 72, discipline: "Deontologia", code: "Estatuto da Ordem dos Advogados", articleNumber: "Artigo 108.º", articleTitle: "Dever de lealdade", articleText: "1 - O advogado deve, em tribunal, agir com lealdade, não procurando conscientemente interpretar de forma errónea as normas jurídicas, nem delas retirar conclusões ilícitas, ou usando de meios ou expedientes ilegais ou desnecessários para demorar o andamento do processo.", question: "Um advogado apresenta sucessivos requerimentos manifestamente infundados com o único propósito de atrasar o andamento do processo. Que dever está a violar?", options: ["O dever de sigilo.", "O dever para com a comunidade.", "O dever de lealdade para com o tribunal.", "O dever de fixar honorários com moderação."], correctAnswerIndex: 2, explanation: "A prática de atos dilatórios e desnecessários constitui uma violação do dever de lealdade para com o tribunal, conforme previsto no Art. 108.º, n.º 1, que exige uma atuação processual correta e honesta." },
    { id: 73, discipline: "Deontologia", code: "Estatuto da Ordem dos Advogados", articleNumber: "Artigo 112.º", articleTitle: "Dever de solidariedade", articleText: "1 - A solidariedade entre advogados deve ser considerada em todos os momentos e traduzir-se no apoio mútuo, na defesa dos interesses legítimos da profissão e na coadjuvação de esforços para o seu engrandecimento e prestígio.", question: "Um advogado recusa-se a ser substituído por um colega numa diligência urgente, sem qualquer justificação. Que dever pode estar a violar?", options: ["O dever de independência.", "O dever de sigilo profissional.", "O dever de solidariedade.", "O dever de lealdade para com o tribunal."], correctAnswerIndex: 2, explanation: "O dever de solidariedade, consagrado no Art. 112.º, implica o apoio mútuo entre colegas. A recusa injustificada de colaboração numa situação de necessidade pode constituir uma violação deste dever." },
    { id: 74, discipline: "Deontologia", code: "Estatuto da Ordem dos Advogados", articleNumber: "Artigo 115.º", articleTitle: "Infração disciplinar", articleText: "1 - Comete infração disciplinar o advogado ou advogado estagiário que, por ação ou omissão, violar dolosa ou culposamente algum dos deveres consagrados no presente Estatuto, nos respetivos regulamentos ou nas demais disposições legais aplicáveis.", question: "Para que um advogado cometa uma infração disciplinar, é necessário que tenha atuado com intenção (dolo)?", options: ["Sim, a infração disciplinar é exclusivamente dolosa.", "Não, a infração pode ser praticada tanto com dolo como com negligência (culpa).", "Apenas as infrações mais graves exigem dolo.", "Não, a responsabilidade disciplinar é objetiva, não depende de dolo ou culpa."], correctAnswerIndex: 1, explanation: "O Art. 115.º, n.º 1, é claro ao estabelecer que a violação dos deveres pode ser 'dolosa ou culposamente', o que significa que tanto a atuação intencional como a negligente podem constituir uma infração disciplinar." },
    { id: 75, discipline: "Deontologia", code: "Estatuto da Ordem dos Advogados", articleNumber: "Artigo 74.º", articleTitle: "Trajo profissional", articleText: "1 - O uso da toga é obrigatório para os advogados e advogados estagiários, quando pleiteiem oralmente.", question: "Um juiz impede um advogado de fazer as suas alegações orais porque este não está a usar toga. A conduta do juiz é correta?", options: ["Sim, o uso de toga é um requisito processual.", "Não, o uso da toga é um dever deontológico, não um pressuposto processual. O juiz deve comunicar a falta à Ordem dos Advogados.", "Sim, mas apenas se a parte contrária o requerer.", "Não, porque o uso da toga é facultativo."], correctAnswerIndex: 1, explanation: "O uso da toga é um dever deontológico (Art. 74.º), não um pressuposto da validade do ato processual. O juiz não pode impedir a intervenção do advogado, mas deve, nos termos do dever de comunicação previsto no Art. 121.º, participar a infração à Ordem dos Advogados." },
    { id: 76, discipline: "Deontologia", code: "Estatuto da Ordem dos Advogados", articleNumber: "Artigo 105.º", articleTitle: "Direito à cobrança de honorários e provisões", articleText: "4 - O advogado goza do direito de retenção sobre os bens, objetos ou documentos do cliente que se encontrem em seu poder por motivo da prestação de serviços profissionais, para garantia do pagamento dos honorários e reembolso de despesas que lhe sejam devidos.", question: "Um cliente recusa-se a pagar os honorários. O advogado pode reter documentos do cliente que estão na sua posse até ser pago?", options: ["Não, deve devolver imediatamente todos os documentos.", "Apenas com autorização judicial.", "Sim, o advogado goza do direito de retenção como garantia de pagamento.", "Não, isso constituiria um crime de apropriação ilegítima."], correctAnswerIndex: 2, explanation: "O Art. 105.º, n.º 4, consagra expressamente o direito de retenção do advogado sobre documentos e bens do cliente que estejam em seu poder, como uma forma de garantir o pagamento dos seus honorários e despesas." },
    { id: 77, discipline: "Deontologia", code: "Estatuto da Ordem dos Advogados", articleNumber: "Artigo 100.º", articleTitle: "Deveres para com o cliente", articleText: "2 - O advogado não deve, sem motivo justificado, cessar o patrocínio das questões que lhe estão cometidas.", question: "Um advogado decide, na véspera de um julgamento, renunciar ao mandato sem qualquer justificação. A sua conduta é deontologicamente correta?", options: ["Sim, o advogado pode renunciar ao mandato livremente.", "Sim, se notificar o tribunal por escrito.", "Não, a cessação do patrocínio sem motivo justificado é uma violação de um dever para com o cliente.", "Apenas se o cliente concordar com a renúncia."], correctAnswerIndex: 2, explanation: "O Art. 100.º, n.º 2, impõe que a cessação do patrocínio por iniciativa do advogado seja justificada. Uma renúncia injustificada, especialmente em momentos críticos do processo, viola os deveres de lealdade e dedicação para com o cliente." },
    { id: 78, discipline: "Deontologia", code: "Estatuto da Ordem dos Advogados", articleNumber: "Artigo 109.º", articleTitle: "Dever de correção", articleText: "1 - O advogado deve abster-se de usar de expressões ou de gestos ofensivos ou desprimorosos para com os magistrados...", question: "Durante uma audiência, um advogado, exaltado, dirige-se ao juiz em termos desrespeitosos. Que dever está a violar?", options: ["O dever de sigilo.", "O dever de correção para com os magistrados.", "O dever de solidariedade para com os colegas.", "O direito de protesto."], correctAnswerIndex: 1, explanation: "O Art. 109.º estabelece o dever de correção, que impõe ao advogado uma conduta urbana e respeitosa para com os magistrados, sendo proibidas expressões ou gestos ofensivos." },
    { id: 79, discipline: "Deontologia", code: "Estatuto da Ordem dos Advogados", articleNumber: "Artigo 111.º", articleTitle: "Relações com as testemunhas", articleText: "O advogado não deve instruir, influenciar ou, por qualquer outro meio, alterar o depoimento das testemunhas, nem com elas estabelecer relações que possam pôr em causa a sua isenção e independência.", question: "Antes de uma audiência, um advogado reúne-se com uma testemunha e diz-lhe exatamente o que deve responder em tribunal. Esta conduta é permitida?", options: ["Sim, faz parte da preparação da prova.", "Apenas se a testemunha for sua cliente noutro processo.", "Não, é uma violação grave do dever de não influenciar as testemunhas.", "Sim, se o fizer na presença do advogado da parte contrária."], correctAnswerIndex: 2, explanation: "O Art. 111.º proíbe categoricamente que o advogado instrua ou influencie o depoimento de testemunhas, pois tal conduta compromete a descoberta da verdade material e a isenção da prova." },
    { id: 80, discipline: "Deontologia", code: "Estatuto da Ordem dos Advogados", articleNumber: "Artigo 113.º", articleTitle: "Correspondência confidencial", articleText: "1 - Sempre que um advogado pretenda que a sua comunicação, dirigida a outro advogado, a um solicitador ou a um agente de execução, tenha caráter confidencial, deve exprimir claramente essa sua intenção.\n2 - A comunicação confidencial é insuscetível de ser revelada e não pode constituir meio de prova.", question: "Uma carta trocada entre dois advogados, marcada como 'Confidencial', pode ser junta a um processo como meio de prova?", options: ["Sim, se for relevante para a decisão.", "Apenas com autorização de ambos os advogados.", "Não, a correspondência confidencial não pode constituir meio de prova em nenhuma circunstância.", "Sim, se o juiz assim o determinar."], correctAnswerIndex: 2, explanation: "O Art. 113.º, n.º 2, estabelece uma proteção absoluta para a correspondência confidencial entre advogados. Esta não pode ser revelada nem utilizada como prova, garantindo um espaço de negociação livre e honesto entre os mandatários." },
    { id: 81, discipline: "Deontologia", code: "Estatuto da Ordem dos Advogados", articleNumber: "Artigo 112.º", articleTitle: "Dever de solidariedade", articleText: "5 - Antes de aceitar assumir o patrocínio de uma questão que tenha sido confiada a outro advogado, deve este certificar-se de que o colega foi notificado da revogação do mandato e de que foram pagos os honorários e outras quantias que sejam devidas àquele...", question: "Um cliente pretende mudar de advogado. O novo advogado, antes de aceitar o mandato, deve fazer o quê?", options: ["Criticar o trabalho do colega anterior para justificar a mudança.", "Aceitar imediatamente para garantir o cliente.", "Certificar-se de que o colega anterior foi notificado da revogação e que os seus honorários foram pagos.", "Pedir autorização à Ordem dos Advogados para aceitar o caso."], correctAnswerIndex: 2, explanation: "O Art. 112.º, n.º 5, impõe ao advogado sucessor um dever de solidariedade para com o colega. Antes de aceitar o patrocínio, deve tomar diligências para garantir que a transição é feita de forma correta, incluindo a questão dos honorários devidos ao advogado anterior." }
];

// --- AUTHENTICATION & PROXY LOGIC ---
const checkAuth = async (req, res, next) => {
    try {
        // We will try to fetch the user's profile from Learnworlds API
        // by forwarding the cookies the user's browser sent to us.
        const response = await axios.get(`${LEARNWORLDS_SCHOOL_URL}/api/v2/users/me`, {
            headers: {
                // Forward all cookies from the incoming request
                'Cookie': req.headers.cookie, 
                'Lw-Client': 'your_client_id_if_needed_for_this_call' // Usually not needed for 'me' endpoint
            }
        });
        
        // If the API call succeeds (status 200), the user is logged in.
        if (response.status === 200) {
            req.user = response.data; // Attach user data to the request for potential future use
            return next(); // Proceed to the next middleware/route handler
        }

        // If for some reason the status is not 200, we treat it as unauthorized
        res.status(401).send('Authentication check failed');

    } catch (error) {
        // If the axios request fails (e.g., Learnworlds returns a 401 or 403),
        // it means the cookies are invalid or the user is not logged in.
        // We then return a 401 Unauthorized error to our frontend.
        res.status(401).send('User not authenticated');
    }
};


// --- API ROUTES ---
app.get('/api/quiz-data', checkAuth, (req, res) => {
    const { discipline } = req.query;

    if (!discipline) {
        return res.status(400).json({ error: 'Discipline parameter is required.' });
    }

    if (discipline === 'Geral') {
        res.json(allQuestions);
    } else {
        const filteredQuestions = allQuestions.filter(q => q.discipline === discipline);
        res.json(filteredQuestions);
    }
});


// --- SERVER START ---
app.listen(PORT, () => {
    console.log(`Server is running on port ${PORT}`);
    console.log(`Frontend URL configured: ${FRONTEND_URL}`);
    console.log(`Learnworlds School URL configured: ${LEARNWORLDS_SCHOOL_URL}`);
});

